idf_component_register(
    SRCS
        "test_main.c"
        "test_framebuffer.c"
        "test_draw.c"
        "test_answers.c"
        "test_statemachine.c"
        "test_listen.c"
        "test_vad.c"
        "test_animation.c"
        "test_render.c"
        "test_gemini_wav.c"
        "test_bloop.c"
        "../../main/gfx/framebuffer.c"
        "../../main/gfx/draw.cpp"
        "../../main/gfx/text.cpp"
        "../../main/scene/answers.cpp"
        "../../main/scene/statemachine.cpp"
        "../../main/scene/listen.c"
        "../../main/scene/vad.c"
        "../../main/scene/bloop.c"
        "../../main/scene/animation.cpp"
        "../../main/net/gemini_wav.c"
        "../../main/render/render.cpp"
        "../../main/render/fx.cpp"
    INCLUDE_DIRS
        "."
        "../../main"
        "../../main/gfx"
        "../../main/scene"
        "../../main/render"
        "../../main/net"
    REQUIRES unity
    WHOLE_ARCHIVE
)
