#!/usr/bin/env python3
"""Regenerate main/gfx/font_montserrat_bold.h from the Montserrat TTF.

The renderer uses its own tiny bitmap-font format rather than a font library:
each glyph is `width * FONT_MB_CELL_H` bytes of 8-bit coverage (alpha), row-major,
and glyphs are looked up by ASCII codepoint through a flat 128-entry table.

The original header was committed without any tooling, which is how it shipped
missing the digits 0-9 -- text_mb_draw() silently advances past a codepoint it has
no glyph for, so "8 Ball" rendered as " Ball" with no error anywhere. This script
exists so the character set is a visible, reproducible decision.

Usage:
    python3 scripts/gen-font.py --ttf Montserrat[wght].ttf \
        > main/gfx/font_montserrat_bold.h

Fetch the font (SIL Open Font License) from:
    https://github.com/google/fonts/tree/main/ofl/montserrat
"""
import argparse
import sys

from PIL import Image, ImageDraw, ImageFont

# Must match the constants baked into the header consumers (gfx/text.cpp).
CELL_H = 44
PT_SIZE = 32
SPACE_W = 14

# The character set the device can display. Anything outside this renders as a
# blank advance, so keep it in sync with what answers/messages can contain:
# letters, digits, and the punctuation the 20 canned answers plus Gemini replies
# actually use.
CHARS = (
    "!',-.?"
    "0123456789"
    "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    "abcdefghijklmnopqrstuvwxyz"
)


def render_glyph(font, ch):
    """Rasterize one character to (width, bytes) of 8-bit coverage.

    Glyphs are drawn against a common baseline so they line up vertically; the
    horizontal bearing is baked into the bitmap, which is why the struct has no
    bearing_x field.
    """
    ascent, _ = font.getmetrics()
    # Oversized scratch canvas, cropped horizontally below.
    img = Image.new("L", (PT_SIZE * 4, CELL_H), 0)
    draw = ImageDraw.Draw(img)
    draw.text((PT_SIZE, ascent), ch, font=font, fill=255, anchor="ls")

    bbox = img.getbbox()
    if bbox is None:          # whitespace-only glyph
        return 0, b""
    x0, _, x1, _ = bbox
    # Keep the left side bearing relative to the pen position.
    x0 = min(x0, PT_SIZE)
    crop = img.crop((x0, 0, x1, CELL_H))
    return crop.width, crop.tobytes()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True, help="path to the Montserrat TTF")
    args = ap.parse_args()

    font = ImageFont.truetype(args.ttf, PT_SIZE)
    try:
        font.set_variation_by_name("Bold")
    except Exception:
        # A static Montserrat-Bold.ttf has no variation axes; that is fine.
        pass

    glyphs = {}
    for ch in CHARS:
        w, data = render_glyph(font, ch)
        if w:
            glyphs[ord(ch)] = (w, data)

    out = sys.stdout.write
    out("#pragma once\n#include <stdint.h>\n#include <stddef.h>\n\n")
    out("// Montserrat Bold 32pt, 8-bit grayscale alpha, row-major, variable width.\n")
    out("// GENERATED by scripts/gen-font.py -- do not hand-edit. Regenerate to change\n")
    out("// the character set (see CHARS in that script).\n")
    out("// Montserrat is licensed under the SIL Open Font License 1.1.\n")
    out("#define FONT_MB_CELL_H  %d  // all glyphs have this height\n" % CELL_H)
    out("#define FONT_MB_SPACE_W %d\n\n" % SPACE_W)
    out("typedef struct {\n"
        "    uint8_t         width;\n"
        "    uint8_t         advance;\n"
        "    const uint8_t  *bitmap; // width * FONT_MB_CELL_H bytes, 8-bit alpha\n"
        "} font_mb_glyph_t;\n\n")

    for cp in sorted(glyphs):
        w, data = glyphs[cp]
        body = ", ".join("0x%02x" % b for b in data)
        out("static const uint8_t _g%d[] = {%s};\n" % (cp, body))

    out("\nstatic const font_mb_glyph_t font_mb[128] = {\n")
    for cp in range(128):
        if cp in glyphs:
            w, _ = glyphs[cp]
            label = chr(cp).replace("*/", "")
            out("    {%d, %d, _g%d},  /* %s */\n" % (w, w + 1, cp, label))
        else:
            out("    {0, 0, NULL},\n")
    out("};\n\n")

    out("// Returns NULL if char not in font.\n"
        "static inline const font_mb_glyph_t *font_mb_get(char c) {\n"
        "    unsigned u = (unsigned char)c;\n"
        "    if (u >= 128 || !font_mb[u].advance) return NULL;\n"
        "    return &font_mb[u];\n"
        "}\n\n")
    out("// Pixel width of a string. MUST agree with how text_mb_draw() advances the pen,\n"
        "// or the wrap measures lines narrower than they render and text overflows the\n"
        "// triangle: a character with no glyph (space, and anything outside the set above)\n"
        "// advances FONT_MB_SPACE_W there, so it has to count for that much here too.\n"
        "static inline int font_mb_str_width(const char *s) {\n"
        "    int w = 0;\n"
        "    for (; *s; s++) {\n"
        "        const font_mb_glyph_t *g = font_mb_get(*s);\n"
        "        w += g ? g->advance : FONT_MB_SPACE_W;\n"
        "    }\n"
        "    return w;\n"
        "}\n")


if __name__ == "__main__":
    main()
