#!/usr/bin/env bash
#
# Install a trained microWakeWord model into the firmware.
#
# Takes the two files the trainer (Colab) produces — a quantized .tflite and its
# .json metadata — and does the whole repo-side wiring described in
# docs/wake-word-runbook.md, Path A steps 2-4 + 7:
#
#   1. xxd -i the .tflite into main/hal/<name>_model.h, with clean symbol names.
#   2. Patch main/hal/wakeword.cpp: the #include, the four WW_* tuning constants
#      (from the .json), and the add_wake_word_model() symbol + label.
#   3. git rm the old model header it replaced.
#
# After this you still: build, flash, say the phrase, tune the cutoff, commit.
#
# Usage:
#   scripts/install-wake-word.sh <model.tflite> <model.json> "Wake Phrase"
#
# Example:
#   scripts/install-wake-word.sh ~/Downloads/magic_8_ball.tflite \
#       ~/Downloads/magic_8_ball.json "Magic 8 Ball"
#
set -euo pipefail

die() { echo "error: $*" >&2; exit 1; }

[ $# -eq 3 ] || die "usage: $0 <model.tflite> <model.json> \"Wake Phrase\""

TFLITE="$1"
JSON="$2"
LABEL="$3"

[ -f "$TFLITE" ] || die "tflite not found: $TFLITE"
[ -f "$JSON" ]   || die "json not found: $JSON"
command -v xxd >/dev/null || die "xxd not on PATH"
command -v jq  >/dev/null || die "jq not on PATH"

# Repo root = parent of this script's dir, so the script works from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
HAL="$ROOT/main/hal"
WW="$HAL/wakeword.cpp"
[ -f "$WW" ] || die "wakeword.cpp not found at $WW"

# Derive a clean C identifier base from the .tflite filename.
#   magic_8_ball.tflite -> magic_8_ball   (symbol: magic_8_ball_tflite)
# C identifiers can't start with a digit, so prefix one if needed.
BASE="$(basename "$TFLITE" .tflite)"
BASE="$(echo "$BASE" | tr -c 'A-Za-z0-9_' '_' | sed 's/__*/_/g; s/^_//; s/_$//')"
[ -n "$BASE" ] || die "could not derive a symbol name from $TFLITE"
case "$BASE" in [0-9]*) BASE="m_$BASE" ;; esac

SYM="${BASE}_tflite"
HEADER="$HAL/${BASE}_model.h"
GUARD="$(echo "${BASE}_MODEL_H" | tr 'a-z' 'A-Z')"

# --- Pull the four tuning constants from the .json --------------------------
# The trainer emits these under their canonical keys. Fall back loudly if a key
# is missing rather than silently shipping a wrong value.
get() {
    local key="$1" val
    val="$(jq -er ".${key} // empty" "$JSON" 2>/dev/null || true)"
    [ -n "$val" ] || die "key '$key' missing from $JSON (can't tune wakeword.cpp safely)"
    echo "$val"
}
CUTOFF="$(get probability_cutoff)"
WINDOW="$(get sliding_window_size)"
STEP="$(get feature_step_size)"
ARENA="$(get tensor_arena_size)"

# Pad the arena to the next 1 KB and keep at least the 48 KB floor we ship today
# (PSRAM, so oversizing is cheap insurance against a silent voice-disable).
ARENA_KB=$(( (ARENA + 1023) / 1024 ))
[ "$ARENA_KB" -lt 48 ] && ARENA_KB=48

# Float cutoffs print as e.g. 0.6 -> append f for the C literal; pass through if
# already suffixed.
case "$CUTOFF" in *f) CUTOFF_C="$CUTOFF" ;; *) CUTOFF_C="${CUTOFF}f" ;; esac

echo ">> phrase           : $LABEL"
echo ">> symbol           : $SYM"
echo ">> header           : ${HEADER#$ROOT/}"
echo ">> probability_cutoff = $CUTOFF_C"
echo ">> sliding_window     = $WINDOW"
echo ">> feature_step_size  = $STEP"
echo ">> tensor_arena       = ${ARENA_KB} KB (json asked $ARENA)"

# --- 1. Generate the C header ----------------------------------------------
# xxd derives the symbol from the input filename; pipe through a tmp copy named
# exactly <BASE>.tflite so the symbol is clean regardless of the source path.
TMP="$(mktemp -d "${TMPDIR:-/tmp}/wwgen.XXXXXX")"
trap 'rm -rf "$TMP"' EXIT
cp "$TFLITE" "$TMP/${BASE}.tflite"
{
    echo "// Embedded \"$LABEL\" microWakeWord TFLite model: ${SYM}[] / ${SYM}_len."
    echo "// Generated by scripts/install-wake-word.sh from $(basename "$TFLITE")."
    echo "#ifndef $GUARD"
    echo "#define $GUARD"
    echo
    ( cd "$TMP" && xxd -i "${BASE}.tflite" )
    echo
    echo "#endif  // $GUARD"
} > "$HEADER"
echo ">> wrote $HEADER"

# --- 2. Patch wakeword.cpp --------------------------------------------------
# Find the current model header include and the add_wake_word_model symbol so we
# replace exactly what's there, whatever it is today.
OLD_INCLUDE="$(grep -oE '#include "[a-zA-Z0-9_]+_model\.h"' "$WW" | head -1 || true)"
[ -n "$OLD_INCLUDE" ] || die "could not find the model #include in wakeword.cpp"
OLD_HEADER_NAME="$(echo "$OLD_INCLUDE" | sed -E 's/.*"([^"]+)".*/\1/')"
OLD_SYM="$(grep -oE 'add_wake_word_model\([a-zA-Z0-9_]+' "$WW" | head -1 | sed 's/add_wake_word_model(//' || true)"
[ -n "$OLD_SYM" ] || die "could not find add_wake_word_model(<symbol> in wakeword.cpp"
JSON_NAME="$(basename "$JSON")"

python3 - "$WW" "$OLD_INCLUDE" "$SYM" "$LABEL" "$CUTOFF_C" "$WINDOW" "$STEP" "$ARENA_KB" "$OLD_SYM" "$BASE" "$CUTOFF" "$ARENA" "$JSON_NAME" <<'PY'
import re, sys
(ww, old_include, sym, label, cutoff, window, step, arena_kb, old_sym, base,
 cutoff_raw, arena_raw, json_name) = sys.argv[1:]
s = open(ww).read()

# include
s = s.replace(old_include, f'#include "{base}_model.h"')

# Provenance comment block: the "Embedded ... model: <sym>[] / _len." line and
# the "<phrase>.json: probability_cutoff ..." line both name the old model.
# Rewrite them so the comments don't rot into a lie about which model ships.
s = re.sub(r'// Embedded "[^"]*" (micro[Ww]ake[Ww]ord )?TFLite model:[^\n]*',
           f'// Embedded "{label}" microWakeWord TFLite model: {sym}[] / {sym}_len.', s)
# Drop the old "Community model from ..." provenance line if present.
s = re.sub(r'\n// Community model from[^\n]*', '', s)
# Match the json comment line plus any immediately-following comment lines that
# carry the remaining tuning values, so we replace the whole block (1-2 lines)
# rather than leaving a stale continuation line behind.
s = re.sub(r'//\s*[A-Za-z0-9_\.]+\.json: probability_cutoff[^\n]*'
           r'(\n//[^\n]*(sliding_window|feature_step_size|tensor_arena)[^\n]*)*',
           f'// {json_name}: probability_cutoff {cutoff_raw}, sliding_window_size {window},\n'
           f'// feature_step_size {step}, tensor_arena_size {arena_raw}.', s)

# tuning constants
s = re.sub(r'(#define\s+WW_PROBABILITY_CUTOFF\s+)\S+', r'\g<1>' + cutoff, s)
s = re.sub(r'(#define\s+WW_SLIDING_WINDOW\s+)\S+',     r'\g<1>' + window, s)
s = re.sub(r'(#define\s+WW_FEATURES_STEP_SIZE\s+)\S+', r'\g<1>' + step,   s)
s = re.sub(r'(#define\s+WW_TENSOR_ARENA_SIZE\s+).*',   r'\g<1>(' + arena_kb + ' * 1024)', s)

# add_wake_word_model symbol + label
s = re.sub(r'add_wake_word_model\(' + re.escape(old_sym), 'add_wake_word_model(' + sym, s)
s = re.sub(r'"' + re.escape(label) + r'"', '"' + label + '"', s)  # no-op if already set
# replace the previous label string in the add_wake_word_model call
s = re.sub(r'(add_wake_word_model\([^;]*?")[^"]*("[,)])',
           lambda m: m.group(1) + label + m.group(2), s, count=1, flags=re.S)

open(ww, 'w').write(s)
print(f">> patched {ww}")
PY

# --- 3. Remove the old model header it replaced -----------------------------
OLD_HEADER_PATH="$HAL/$OLD_HEADER_NAME"
if [ "$OLD_HEADER_NAME" != "${BASE}_model.h" ] && [ -f "$OLD_HEADER_PATH" ]; then
    if git -C "$ROOT" ls-files --error-unmatch "$OLD_HEADER_PATH" >/dev/null 2>&1; then
        git -C "$ROOT" rm -q "$OLD_HEADER_PATH"
        echo ">> git rm $OLD_HEADER_NAME (old model)"
    else
        rm -f "$OLD_HEADER_PATH"
        echo ">> rm $OLD_HEADER_NAME (old model, was untracked)"
    fi
fi

git -C "$ROOT" add "$HEADER" "$WW"

cat <<EOF

Done. Next:
  1. idf.py build
  2. idf.py -p <PORT> flash monitor   # watch for "wake-word detector running"
  3. Say "$LABEL"; confirm the detection logs.
  4. Tune WW_PROBABILITY_CUTOFF if it false-triggers (raise) or misses (lower).
  5. git -c commit.gpgsign=false commit -m "feat(hal): switch wake word to '$LABEL'"
EOF
